[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
ci = "github"
installers = ["shell", "homebrew"]
tap = "km-tr/homebrew-tap"
publish-jobs = ["homebrew"]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]

[dist.bin-aliases]
"worktree-link" = ["wtl"]

[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-24.04-arm"

